- name: Create Droplet
  hosts: localhost
  tasks:
    - name: Create Droplet
      command: python3 ../src/droplet/create.py

    - name: Wait for Digital Ocean
      ansible.builtin.pause:
        minutes: 1

    - name: Assign IP to Droplet
      command: python ../src/droplet/assign.py
