name: Run Pytest Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      test_result: ${{ job.status }} # stores the result of the job.

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r test/requirements.txt
      - name: Run tests with pytest
        run: pytest

  trigger-docker-build:
    runs-on: ubuntu-latest
    needs: run-tests
    if: ${{ needs.run-tests.outputs.test_result == 'success' }} # only run if tests pass
    steps:
      - name: Dispatch Docker Build Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: docker-build-event
